version: '2.2'

services:
  openhab:
    image: "openhab/openhab:2.4.0"
    container_name: openhab
    restart: always
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "${PWD}/openhab_addons:/openhab/addons"
      - "${PWD}/openhab_conf:/openhab/conf"
      - "${PWD}/openhab_userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
    ports:
      - "8080:8080"
      - "8443:8443"
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    network_mode: host
    ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
    - "25826:25826/udp"
    - "2003:2003"
    env_file:
      # Check the file to set default password!
      - "${PWD}/env.influxdb"
    volumes:
    - "${PWD}/influxdb/data:/var/lib/influxdb/"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    network_mode: host
    ports:
    - "3000:3000"
    env_file:
    - "${PWD}/env.grafana"
    volumes:
    - "${PWD}/grafana/data:/var/lib/grafana/"
  nodered:
    image: nodered/node-red-docker:latest
    container_name: nodered
    restart: always
    network_mode: host
    user: root
    ports:
    - "1880:1880"
    volumes:
    - ./nodered:/data
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    network_mode: host
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "${PWD}/mosquitto/conf:/mosquitto/config/"
      - "${PWD}/mosquitto/data/:/mosquitto/data/"
      - "${PWD}/mosquitto/log/:/mosquitto/log/"
